name: lotus_env
channels:
  - conda-forge
dependencies:
  - chembl_structure_pipeline >=1.2.0
  - conda-build >=2.1.5
  - openjdk
  - pandas >=2.2.2
  - python >=3.11
  - rdkit >=2024.3.6
  - scipy >=1.13
  - r-base >=4.3.3
  - r-clisymbols ## needed by classyfirer
  - r-codetools
  - r-data.table
  - r-dplyr
  - r-DBI
  - r-forcats
  - r-future
  - r-future.apply
  - r-gdata
  - r-httr
  - r-jsonlite
  # - r-philentropy
  - r-plotly
  - r-progressr
  - r-purrr
  - r-rcrossref
  - r-RCurl
  - r-readr
  - r-readxl
  - r-remotes
  - r-rentrez
  # - r-rotl
  # - r-RPostgreSQL
  - r-RSQLite
  - r-R.utils ## needed for new version of data.table to read .gz
  - r-rvest
  - r-splitstackshape
  - r-stringdist
  - r-stringi
  - r-stringr
  - r-testthat
  - r-tibble
  - r-tidyjson
  - r-tidyr
  - r-XML
  - r-xml2
